name: integration tests

on:
  workflow_dispatch:

jobs:
  e2e-test-k3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/ensure-pack
      - name: build kyma@v3 binary
        run: make build
      - uses: kyma-project/serverless/.github/actions/create-k3d-cluster@9e8c091842e5c884e1770ef0bcc5b4b4d2894b74
      - name: test 
        run: make -C tests/k3d e2e-test

  e2e-test-btp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/ensure-pack
      - name: compute github commit sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: build kyma@v3 binary
        run: make build
      - uses: kyma-project/terraform-module/.github/actions/create-sap-btp-kyma@0635a02ed7c63944f2e544d27603f3d2c72fee2b
        id: create-btp-resources
        with:
          btp_subaccount_name: cli-test-${{ steps.vars.outputs.sha_short }}-${{ github.run_attempt }}
          btp_backend_url: '${{ secrets.BTP_BACKEND_URL}}'
          btp_user: '${{ secrets.BTP_BOT_USER}}'
          btp_password: '${{ secrets.BTP_BOT_PASSWORD}}'
          btp_global_account: '${{ secrets.BTP_GLOBAL_ACCOUNT }}'
          btp_idp_tenant: '${{ secrets.BTP_CUSTOM_IAS_TENANT }}'
          btp_subaccount_region: '${{ secrets.BTP_SUBACCOUNT_REGION }}'
          btp_kyma_region: '${{ secrets.BTP_KYMA_REGION }}'
          btp_kyma_plan: '${{ secrets.BTP_KYMA_PLAN }}'
      - name: test 
        run: |
          TF_VAR_BTP_BACKEND_URL=$TF_VAR_BTP_BACKEND_URL \
          TF_VAR_BTP_BOT_USER=$TF_VAR_BTP_BOT_USER \
          TF_VAR_BTP_BOT_PASSWORD=$TF_VAR_BTP_BOT_PASSWORD \
          TF_VAR_BTP_CUSTOM_IAS_TENANT=$TF_VAR_BTP_CUSTOM_IAS_TENANT \
          TF_VAR_BTP_GLOBAL_ACCOUNT=$TF_VAR_BTP_GLOBAL_ACCOUNT \
          TF_VAR_BTP_KYMA_SUBACCOUNT_ID=$TF_VAR_BTP_KYMA_SUBACCOUNT_ID \
          TF_VAR_BTP_OBJECTSTORE_SUBACCOUNT_ID=$TF_VAR_BTP_OBJECTSTORE_SUBACCOUNT_ID \
          TF_VAR_BTP_HANA_SUBACCOUNT_ID=$TF_VAR_BTP_HANA_SUBACCOUNT_ID \
          DOMAIN=$DOMAIN \
          make -C tests/btp e2e-test
        env:
          TF_VAR_BTP_BACKEND_URL: '${{ secrets.BTP_BACKEND_URL}}'
          TF_VAR_BTP_BOT_USER: '${{ secrets.BTP_BOT_USER}}'
          TF_VAR_BTP_BOT_PASSWORD: '${{ secrets.BTP_BOT_PASSWORD}}'
          TF_VAR_BTP_CUSTOM_IAS_TENANT: '${{ secrets.BTP_CUSTOM_IAS_TENANT }}'
          TF_VAR_BTP_GLOBAL_ACCOUNT: '${{ secrets.BTP_GLOBAL_ACCOUNT }}'
          TF_VAR_BTP_KYMA_SUBACCOUNT_ID: '${{ steps.create-btp-resources.outputs.subaccount_id }}'
          TF_VAR_BTP_OBJECTSTORE_SUBACCOUNT_ID: '${{ secrets.BTP_OBJECTSTORE_SUBACCOUNT_ID }}'
          TF_VAR_BTP_HANA_SUBACCOUNT_ID: '${{ secrets.BTP_HANA_SUBACCOUNT_ID }}'
          DOMAIN: '${{ steps.create-btp-resources.outputs.domain }}'
      - uses: kyma-project/terraform-module/.github/actions/force-delete-sap-btp-subaccount@0635a02ed7c63944f2e544d27603f3d2c72fee2b
        if: always()
        with:
          btp_subaccount_id: ${{ steps.create-btp-resources.outputs.subaccount_id }}
          btp_backend_url: ${{ secrets.BTP_BACKEND_URL}}
          btp_user: ${{ secrets.BTP_BOT_USER}}
          btp_password: ${{ secrets.BTP_BOT_PASSWORD}}
          btp_global_account: ${{ secrets.BTP_GLOBAL_ACCOUNT }}
          btp_idp_tenant: ${{ secrets.BTP_CUSTOM_IAS_TENANT }}